### ISSUE TITLE
If there's no readme I don't know what this does!!!

### ISSUE THREAD

**Issue by nnashwin** [nukr/refill#1]
Yo bro,
I am a fan of yours and want to see what you are working on / what your repos do.
If you do not write what your code does, I can't learn from it!

Well I can, but it's not as cool / convenient.
Please remedy this problem.

**Comment by nukr** [comment]
Hey my friend,

This project is not worth to learn. It's just simply read all data from rethinkdb and then insert into elasticsearch. My (not good) approach is restricted to specific database schema (like my company).

Add a readme still a good idea even if I want to abandon this project. 

BUT I AM SO LAZY ... 🤣
